kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config
  namespace: demo
  labels:
    app: app-config
data:
  application.yml: |
    server:
      servlet:
        context-path: /v2
      port: 8080