kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: app-secret
  namespace: demo
  labels:
    app: app-secret
data:
  application.yml: aHR0cDoKICBiYXNpYzoKICAgIHVzZXJuYW1lOiAiYWxsZW4iCiAgICBwYXNzd29yZDogInBhc3N3b3JkIg==
