apiVersion: v1
kind: Service
metadata:
  name: app-v1-svc
  namespace: demo
  labels:
    app: app-v1-svc
    version: v1
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31514
  selector:
    app: app-pod
    version: v1
