apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-deploy
  namespace: demo
  labels:
    k8s-app: app-deploy
    version: v1
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: 'RollingUpdate'
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata: 
      labels:
        app: app-pod
        version: v1
      namespace: demo
    spec:
      containers:
      - name: app-dock
        image: k8s-learn:0.0.1-SNAPSHOT
        env:
          - name: CONFIG_LOC
            value: file:/config/,file:/secret/
          - name: MAX_HEAP
            value: "1024M"
        args:
          - '-o'
          - '-Djava.security.egd=file:/dev/./urandom'
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /v2/learn/status
            port: ui-port
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v2/learn/status
            port: ui-port
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
        ports:
        - containerPort: 8080
          name: ui-port
        resources:
          requests:
            memory: "1Gi"
            cpu: "1024m"
          limits:
            memory: "1Gi"
            cpu: "1024m"
        volumeMounts:
        - mountPath: /var/log
          name: log-volume
        - mountPath: /config
          name: config-volume
        - mountPath: /secret
          name: secret-volume
      volumes:
      - name: log-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: app-config
          items:
          - key: application.yml
            path: application.yml
            mode: 0755
      - name: secret-volume
        secret:
          secretName: app-secret
          items:
          - key: application.yml
            path: application.yml
            mode: 0755
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: scribe-deploy
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 60
      type: Resource
    - resource:
        name: memory
        targetAverageUtilization: 60
      type: Resource